config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Christopher Ralph</h3>
    <nav class="nav nav-masthead">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About Me", about_me_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">Using Bootstrap's blog template and a Ruby on Rails course, I've learned how to build this site.</p>
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
      <div class="container">
        <nav class="nav blog-nav">
          <%= link_to "Home", root_path, class: 'nav-link'  %>
          <%= link_to "About Me", about_me_path, class: 'nav-link'  %>
          <%= link_to "Contact", contact_path, class: 'nav-link'  %>
          <%= link_to "Blog", blogs_path, class: 'nav-link'  %>
          <%= link_to "Portfolio", portfolios_path, class: 'nav-link'  %>
          <%= login_helper 'nav-link' %>
        </nav>
      </div>
    </div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>I'm an analytical and empathetic Technical Support Engineer with deep experience in the general SaaS and e-commerce spaces. I enjoy solving complex problems and learning new technologies. I aspire to one day be able to perform full-stack development tasks and this portfolio site is my first attempt at something like that. To get this site going, I followed along in and learned from a Udemy course titled <em><a href='https://www.udemy.com/share/101Xzc3@4ma7Syf9ArKAnTirsTmM1tUxdY2NmwIOmYAu-47KvLMwoAKcZxwGtXDFG6mfeovqAg==/'>Dissecting Ruby on Rails 5 - Become a Professional Developer</a></em>.</p>
  </div>
  
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href='https://github.com/ralph734c' target="_blank"><%= fa_icon "github" %></a></li>
      <li><a href='https://www.linkedin.com/in/ralph734c/' target="_blank"><%= fa_icon "linkedin" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">I stared this journey learning Ruby on Rails and it has started to expand into a few other technologies as well. As my skills grow and improve, so will the projects listed here (ideally.)</p>
    <p>
      <%= link_to 'Learn more about me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'Contact me to partner on a project!', contact_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">This is the start of my portfolio. I'm an aspiring full stack engineer who enjoys working in customer-facing roles and these are examples of projects using the various technologies that I'm learning. I started out learning Ruby on Rails and upskilled from there.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <li><%= link_to "Home", root_path, class: 'text-white' %></li>
          <li><%= link_to "About Me", about_me_path, class: 'text-white' %></li>
          <li><%= link_to "Contact", contact_path, class: 'text-white' %></li>
          <li><%= link_to "Blog", blogs_path, class: 'text-white' %></li>
          <li><%= link_to "Portfolio", portfolios_path, class: 'text-white' %></li>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
  </div>
  <div class="navbar navbar-dark bg-dark">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Christopher Ralph</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>